### ISSUE TITLE
Reset data cache on install

### ISSUE THREAD

**Issue by andrewheusser** [ContextLab/hypertools#194]
Problems can arise if the user has an outdated dataset cached on their computer.  This could be resolved if we reset that data cache upon install/reinstall.

**Comment by paxtonfitzpatrick** [comment]
Since not all hypertools updates involve changes to the datasets, they don't necessarily need to be removed and re-downloaded every time. However, as of [v0.8.0](https://github.com/ContextLab/hypertools/releases/tag/v0.8.0), hypertools now throws a `HypertoolsIOError` suggesting deleting the dataset cache when loading an example dataset fails (because it was created using an an older hypertools version). 

https://github.com/ContextLab/hypertools/blob/564c1d43da447da68ce3d76f51306725291630e0/hypertools/tools/load.py#L169-L187
