### ISSUE TITLE
dependencies bump to allow scikit-learn 0.22

### ISSUE THREAD

**Issue by danieltomasz** [ContextLab/hypertools#237]
In the last version of dependencies is stated scikit-learn<0.22,  is there any reason to hold it on 0.21?

**Comment by paxtonfitzpatrick** [comment]
hi @danieltomasz, so sorry for the delay!  We disallowed `scikit-learn==0.22` because of a bug in the `CountVectorizer` class.  The bug's been fixed in 0.23, so I've bumped the dependency spec to allow `scikit-learn>=0.19.1,!=0.22` in the new release. You can `pip install --upgrade hypertools` to get it.
